# --- GESTIONE ENERGIA DONGLE ---
# Il dongle è alimentato via USB, non deve mai spegnersi
CONFIG_ZMK_SLEEP=n

# Forza il Dongle a richiedere lo stato della batteria alle due metà
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
