# --- GESTIONE ENERGIA DONGLE ---
# Il dongle è alimentato via USB, non deve mai spegnersi
CONFIG_ZMK_SLEEP=n

# --- IMPOSTAZIONI DISPLAY PROSPECTOR ---
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
