# Disabilita il Deep Sleep per risposta istantanea al wakeup
CONFIG_ZMK_SLEEP=n

# Potenza di trasmissione massima per stabilità segnale tra le metà e l'host
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Funzionalità sperimentali BLE per stabilità riconnessioni
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Ripristina 2M PHY per maggiore velocità di trasmissione/handshake
CONFIG_BT_CTLR_PHY_2M=y

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_POINTING=y

CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
