# Prospector è sempre il central
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Numero di periferiche (Temper left + right)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Numero totale connessioni BLE (peripherals + profili host)
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# USB HID (il dongle parla USB al PC)
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
